### ISSUE TITLE
Beta release

### ISSUE THREAD

**Issue by spdegabrielle** [nixin72/from-template#5]
Checklist for beta release on slack before official release in Racket News 14-Sep

Pull requests
 - [x] #2 linux error checking
 - [x] #1 added windows support
 - [x] #4 macOS support
 - [x] #6 Made Linux and Windows versions use https instead of ssh
 - [x] #7 add scribble

Other
 - [x] pass tests on https://pkgs.racket-lang.org/package/from-template

Beta
 - [ ] slack Beta testers linux
 - [ ] slack Beta testers windows
 - [ ] slack Beta testers macOS 
 - [ ] Text for Racket-News by 11- Sep

**Comment by spdegabrielle** [comment]
@soapdog @nixin72

**Comment by nixin72** [comment]
So what needs to be done to make it pass the tests on https://pkgs.racket-lang.org/package/from-template? I've never uploaded a package for Racket before, so unsure what I need to do.

**Comment by spdegabrielle** [comment]
it complaining about lack of a scribble file I think. I'll make a PR give me 30 minutes!

**Comment by spdegabrielle** [comment]
@nixin72 pr #7 should resolve the issue with the tests on https://pkgs.racket-lang.org/package/from-template

**Comment by spdegabrielle** [comment]
once the docs build we can change the readme to refer to them

https://github.com/nixin72/from-template/blob/master/README.md

**Comment by spdegabrielle** [comment]
corrected link in info.rkt
